kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-etc-pv-claim
  namespace: motioneye  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-lib-pv-claim
  namespace: motioneye  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
