
apiVersion: v1
kind: ServiceAccount
metadata:
  name: privileged-sa
  namespace: motioneye  

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-sa
  namespace: motioneye  
subjects:
  - kind: ServiceAccount
    name: privileged-sa
    namespace: motioneye
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'

